---

# install mondoo package which installs cnquery and cnspec
- name: Install mondoo package on Debian
  ansible.builtin.include_tasks: pkg_debian.yml
  when: ansible_os_family == "Debian"

- name: Install mondoo package on Red Hat
  ansible.builtin.include_tasks: pkg_rhel.yml
  when: ansible_os_family == "RedHat"

- name: Install mondoo package on Suse
  ansible.builtin.include_tasks: pkg_suse.yml
  when: ansible_os_family == "Suse"

- name: Login to Mondoo Platform
  ansible.builtin.include_tasks: linux_login.yml
  when: registration_token != ""
