# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

---

# install mondoo package which installs cnquery and cnspec
- name: Install mondoo package on Debian
  ansible.builtin.include_tasks: pkg_debian.yml
  when: ansible_os_family == "Debian"

- name: Install mondoo package on Red Hat
  ansible.builtin.include_tasks: pkg_rhel.yml
  when: ansible_os_family == "RedHat"

- name: Install mondoo package on Photon OS
  ansible.builtin.include_tasks: pkg_photon.yml
  when: ansible_os_family == "VMware Photon OS"

- name: Install mondoo package on Suse
  ansible.builtin.include_tasks: pkg_suse.yml
  when: ansible_os_family == "Suse"

- name: Create update Task
  ansible.builtin.include_tasks: linux_update.yml
  when: update_linux_enabled

- name: Login to Mondoo Platform
  ansible.builtin.include_tasks: linux_login.yml
  when: registration_token != ""
