# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

---

- name: Linux
  ansible.builtin.include_tasks: linux.yml
  when: ansible_system == "Linux"

- name: Windows
  ansible.builtin.include_tasks: windows.yml
  when: ansible_system == "Win32NT"
