# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

---

- name: Install gpg
  ansible.builtin.apt:
    name: gpg
    state: present
    update_cache: yes
  become: true
  when: not ansible_check_mode

- name: Add Mondoo apt repository key.
  ansible.builtin.get_url:
    url: "{{ mondoo_deb_gpgkey }}"
    dest: "/etc/apt/trusted.gpg.d/mondoo.asc"
    mode: '0644'
    force: true
  become: true
  when: not ansible_check_mode

- name: Pack Mondoo gpg key
  ansible.builtin.command: gpg --dearmor --batch --yes --output {{ mondoo_deb_gpgkey_dest }} /etc/apt/trusted.gpg.d/mondoo.asc
  changed_when: false
  no_log: true
  become: "{{ use_become }}"

- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: yes
  become: true
  when: not ansible_check_mode

- name: Configure Mondoo deb repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ mondoo_deb_gpgkey_dest }}] {{ mondoo_deb_repo }}"
    filename: "mondoo"
    state: "present"
    update_cache: yes
  become: "{{ use_become }}"
  when: not ansible_check_mode

- name: Ensure cnquery and cnspec are installed
  ansible.builtin.apt:
    name: mondoo
    state: latest
    update_cache: yes
  become: "{{ use_become }}"
  when: not ansible_check_mode

- name: Ensure cron is installed
  ansible.builtin.apt:
    name: cron
    state: latest
    update_cache: yes
  become: "{{ use_become }}"
  when: not ansible_check_mode and update_linux_enabled

- name: Ensuring unmasked cron.service
  ansible.builtin.systemd:
    name: cron.service
    masked: no
  when: update_linux_enabled

- name: Configuring cron.service
  ansible.builtin.service:
    name: cron.service
    state: started
    enabled: yes
  when: update_linux_enabled
