---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
  become: true
  when: not ansible_check_mode

- name: Add Mondoo apt repository key.
  ansible.builtin.get_url:
    url: "{{ mondoo_deb_gpgkey }}"
    dest: "/etc/apt/trusted.gpg.d/mondoo.asc"
    mode: '0644'
    force: true
  become: true
  when: not ansible_check_mode

- name: Pack Mondoo gpg key
  command: gpg --dearmor --batch --yes --output {{ mondoo_deb_gpgkey_dest }} /etc/apt/trusted.gpg.d/mondoo.asc
  become: true

- name: Configure Mondoo deb repository
  apt_repository:
    repo: "deb [signed-by={{ mondoo_deb_gpgkey_dest }}] {{ mondoo_deb_repo }}"
    filename: "mondoo"
    state: "present"
    update_cache: yes
  become: true
  when: not ansible_check_mode

- name: Ensure cnquery and cnspec are installed
  apt:
    name: mondoo
    state: latest
    update_cache: yes
  become: true
  when: not ansible_check_mode
