---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  become: true
  when: not ansible_check_mode

- name: Install Mondoo apt-key
  apt_key:
    id: E3CCC5777260B0111C49FAD9AC3310C8D750A058
    url: "{{ mondoo_deb_gpgkey }}"
    state: present
  become: true
  when: not ansible_check_mode

- name: Configure Mondoo DEB repository
  apt_repository:
    repo: "{{ mondoo_deb_repo }}"
    state: "present"
    update_cache: yes
  become: true
  when: not ansible_check_mode

- name: Ensure Mondoo agent is installed
  apt:
    name: mondoo
    state: latest
    update_cache: yes
  become: true
  when: not ansible_check_mode
  notify: restart mondoo-service