---

# download the latest json to fetch the latest released version

- name: Determine latest released version
  ansible.windows.win_uri:
    url: "{{ latest_version_url }}"
    return_content: yes
  register: latest_jsondata
  when: pkg_version_url is undefined

- name: Log latest version
  ansible.builtin.debug:
    var: latest_jsondata.json
  when: pkg_version_url is undefined

- name: Determine latest pkg version
  ansible.builtin.set_fact:
    pkg_version_url: "{{ latest_jsondata.json | json_query(jmesquery) }}"
  vars:
    jmesquery: "files[*].filename | [?contains(@, 'msi')] | [0]"
  when: pkg_version_url is undefined

- name: Log latest version
  ansible.builtin.debug:
    var: pkg_version_url

# download and install msi
# we do register as part of the msi workflow to support reregistration more easily
- name: Install Mondoo msi package
  ansible.windows.win_package:
    path: "{{ pkg_version_url }}"
    state: present

- name: Logout cnquery and cnspec from Mondoo platform
  ansible.windows.win_command: cnspec.exe logout --force --config C:\\ProgramData\\Mondoo\\mondoo.yml
  args:
    chdir: "C:\\Program Files\\Mondoo"
    # only run the command if no config file exists
    creates: C:\ProgramData\Mondoo\mondoo.yml
  when: force_registration
  # if the credentials are already invalid, the command will throw an error
  ignore_errors: true

- name: Remove existing credentials
  # ensure no configuration file exists if force mode was activated
  ansible.windows.win_file:
    state: absent
    path: C:\ProgramData\Mondoo\mondoo.yml
  when: force_registration

- name: Store cnspec login command as string
  ansible.builtin.set_fact:
    login_cmd: "cnspec.exe login --config C:\\ProgramData\\Mondoo\\mondoo.yml --token {{ registration_token }}"

- name: Add api-proxy to cnspec login command
  ansible.builtin.set_fact:
    login_cmd: "{{ login_cmd + ' --api-proxy ' + proxy_env['https_proxy'] }}"
  when: proxy_env['https_proxy'] is defined

- name: Login cnquery and cnspec
  ansible.windows.win_command: "{{ login_cmd }}"
  args:
    chdir: "C:\\Program Files\\Mondoo"
    # only run the command if no config file exists (was not deleted in non-force mode)
    creates: C:\ProgramData\Mondoo\mondoo.yml
  when: not ansible_check_mode

- name: Set Mondoo startup mode to auto and ensure it is started
  ansible.windows.win_service:
    name: Mondoo
    start_mode: auto
    state: started
  when: not ansible_check_mode

- name: Ensure cnquery and cnspec are managed
  ansible.windows.win_command: cnspec.exe login
  args:
    chdir: "C:\\Program Files\\Mondoo"
  when: (ensure_managed_client is not undefined and ensure_managed_client) and not ansible_check_mode
