# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

---
# handlers file for cnspec service

- name: Restart cnspec-service
  ansible.builtin.systemd:
    name: cnspec
    state: restarted
    daemon_reload: yes
  when: not ansible_check_mode
