---
dependency:
  name: galaxy
lint: |
  yamllint
  ansible-lint
  flake8
driver:
  name: docker
platforms:
  - name: instance
    image: ${image:-""}
    command: ${container_command:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    # show which tests where executed in test output
    v: 1
