---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${image}:${tag:-latest}
    command: ${container_command:-"/lib/systemd/systemd"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw  # this needs rw to get access to /tmp
    privileged: true
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
      - SYS_TIME
      - LINUX_IMMUTABLE
provisioner:
  name: ansible
verifier:
  name: ansible
