---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: ubuntu
    box: ubuntu/bionic64
  - name: centos
    box: centos/7
  - name: suse
    box: opensuse/openSUSE-15.0-x86_64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  lint:
    name: flake8
  options:
    # show which tests where executed in test output
    v: 1
