---
name: Ansible Lint
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main

  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Copywrite
        uses: hashicorp/setup-copywrite@v1.1.2

      - name: Check Header Compliance
        run: copywrite headers --plan
